export { registerTask } from './register-task'
export { runRegisteredTasks } from './run-registered-tasks'
export { registerStep } from './register-step'
export { ShellPipeSink, wrapCommand } from '../support'
export type { ExecuteFunctionArguments, SetFunction, ExecuteFunction } from '../support'
export { Task } from '../core'
