# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy

on:
  push:
    branches: [ master ]

concurrency:
  group: master
  cancel-in-progress: true

jobs:

  prepare:
    name: Check CI
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  typecheck:
    name: Check types
    needs: [ prepare ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run typecheck

  test:
    name: Unit test
    needs: [ prepare ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run test:ci

  lint:
    name: Lint source
    needs: [ prepare ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint

  bump:
    name: Bump version
    needs:
      - typecheck
      - test
      - lint
    runs-on: ubuntu-latest
    outputs:
      previousVersion: ${{ steps.previousVersion.outputs.version }}
      nextVersion: ${{ steps.nextVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: node -pe "process.stdout.write('::set-output name=version::'); require('./package.json').version"
        id: 'previousVersion'
      - uses: phips28/gh-action-bump-version@v9.0.13
        with:
          major-wording: 'release:'
          minor-wording: 'feat:'
          patch-wording: 'fix:,chore:'
          commit-message: 'ci: bumps version to {{version}}'
      - run: node -pe "process.stdout.write('::set-output name=version::'); require('./package.json').version"
        id: 'nextVersion'

  build:
    name: Build package
    needs: [ bump ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.bump.outputs.nextVersion }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Archive dist/
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1

  publish:
    name: Publish package
    needs:
      - build
      - bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.bump.outputs.nextVersion }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v2
        name: Download dist/
        with:
          name: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Archive pacakge
        uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: |
            '**/**'
            '!node_modules'
