# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy

on:
  push:
    branches: [ master ]

concurrency:
  group: master
  cancel-in-progress: true

jobs:

  prepare:
    name: Check CI
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, 'ci:')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    name: Build package
    needs: [ prepare ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Archive dist/
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1

  test:
    name: Unit test
    needs: [ prepare ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run test:ci

  lint:
    name: Lint source
    needs: [ prepare ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint

  publish:
    name: Publish package
    needs:
      - lint
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Download dist/
        uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node -pe "process.stdout.write('Current package.json version '); require('./package.json').version"
      - uses: phips28/gh-action-bump-version@v9.0.13
        with:
          major-wording: 'release:'
          minor-wording: 'feat:'
          patch-wording: 'fix:,chore:'
          skip-tag: 'true'
          commit-message: 'ci: bumps version to {{version}}'
      - run: node -pe "process.stdout.write('Current package.json version '); require('./package.json').version"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
